/*SELECT BAIRRO_ASS, COUNT(*) AS QUANT_OCORRENCIAS FROM `chamados156` WHERE DESCRICAO LIKE '%morcego%' GROUP BY BAIRRO_ASS ORDER BY QUANT_OCORRENCIAS DESC*/

SELECT COUNT(*) AS QUANT_OCORRENCIAS 
FROM `chamados156` 
WHERE DESCRICAO LIKE '%morcego%'
