SELECT 'ASSALTO', COUNT(*) AS QUANT_OCORRENCIAS 
FROM `chamados156` 
WHERE DESCRICAO LIKE '%assalto%'
 
/*SELECT 'BRIGA', COUNT(*) AS QUANT_OCORRENCIAS 
FROM `chamados156` 
WHERE DESCRICAO LIKE '%briga%'

SELECT 'MORCEGO', COUNT(*) AS QUANT_OCORRENCIAS 
FROM `chamados156` 
WHERE DESCRICAO LIKE '%morcego%' */
